# Generated by Django 4.2.9 on 2024-02-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('web', models.CharField(blank=True, choices=[('Front End', 'Front End'), ('Back End', 'Back End'), ('Full Stack Website', 'Full Stack Website'), ("I'm not sure yet", "I'm not sure yet")], max_length=50, null=True)),
                ('days', models.CharField(blank=True, choices=[('2 - 4 weeks', '2 - 4 weeks'), ('1 - 2 Months', '1 - 2 Months'), ('More than 2 months', 'More than 2 months')], max_length=50, null=True)),
                ('text', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('write_review', models.TextField(max_length=1000)),
                ('profile', models.ImageField(upload_to='images')),
            ],
        ),
    ]
