# Generated by Django 4.2.7 on 2024-04-28 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('web', models.CharField(blank=True, choices=[('Front End', 'Front End'), ('Back End', 'Back End'), ('Full Stack Website', 'Full Stack Website'), ("I'm not sure yet", "I'm not sure yet")], max_length=50, null=True)),
                ('days', models.CharField(blank=True, choices=[('2 - 4 weeks', '2 - 4 weeks'), ('1 - 2 Months', '1 - 2 Months'), ('More than 2 months', 'More than 2 months')], max_length=50, null=True)),
                ('text', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('position', models.CharField(default='', max_length=50)),
                ('write_review', models.TextField(default='', max_length=1000)),
                ('profile', models.ImageField(default='', upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='User_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('profile', models.ImageField(blank=True, default=None, null=True, upload_to='images')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default=None, max_length=6, null=True)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(default='+91', max_length=128, region=None)),
                ('pro', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=2000)),
                ('pro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portfolio_app.user_file')),
            ],
        ),
    ]
