# Generated by Django 4.2.7 on 2024-04-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile',
            field=models.ImageField(blank=True, default='/static/images/profile.webp', null=True, upload_to='images'),
        ),
    ]
