# Generated by Django 4.2.9 on 2024-02-27 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio_app', '0002_user_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=2000)),
                ('pro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portfolio_app.user_file')),
            ],
        ),
        migrations.CreateModel(
            name='user_about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position1', models.CharField(max_length=50)),
                ('profile1', models.ImageField(upload_to='images')),
                ('gender1', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('mobile1', models.IntegerField()),
                ('pro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portfolio_app.user_file')),
            ],
        ),
    ]
