# Generated by Django 4.2.7 on 2024-06-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_category_image_gallerycategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
