# Generated by Django 4.2.9 on 2024-03-01 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_user_file_user_info_user_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='img',
            name='name',
        ),
        migrations.RemoveField(
            model_name='img',
            name='position',
        ),
        migrations.RemoveField(
            model_name='img',
            name='profile',
        ),
        migrations.DeleteModel(
            name='User_data',
        ),
    ]
