# Generated by Django 4.2.9 on 2024-01-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_alter_img_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
