# Generated by Django 4.2.9 on 2024-03-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_remove_img_name_remove_img_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='img',
            name='position',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='img',
            name='profile',
            field=models.ImageField(default='', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='img',
            name='write_review',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
