# Generated by Django 4.2.7 on 2024-04-28 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_alter_userprofile_gender_alter_userprofile_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=2000)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portfolio_app.userprofile')),
            ],
        ),
    ]
