# Generated by Django 4.2.7 on 2024-06-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_userreview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/Galary/'),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/Galary/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile',
            field=models.ImageField(blank=True, default='/static/images/profileimage.png', null=True, upload_to='static/profile'),
        ),
    ]
