# Generated by Django 4.2.7 on 2024-04-28 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_userreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreview',
            old_name='profile',
            new_name='profile_name',
        ),
    ]
