# Generated by Django 4.2.14 on 2024-07-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_alter_category_image_alter_gallerycategory_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, default='Enter Profession', max_length=50, null=True),
        ),
    ]
