# Generated by Django 4.2.9 on 2024-01-20 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_alter_img_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='img',
            old_name='img',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='img',
            old_name='text',
            new_name='write_review',
        ),
    ]
