# Generated by Django 4.2.9 on 2024-01-23 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0007_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
