# Generated by Django 4.2.9 on 2024-01-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0009_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='days',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='web',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
