# Generated by Django 4.2.9 on 2024-01-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0010_contact_days_contact_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='days',
            field=models.CharField(blank=True, choices=[('2 - 4 weeks', '2 - 4 weeks'), ('1 - 2 Months', '1 - 2 Months'), ('More than 2 months', 'More than 2 months')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='web',
            field=models.CharField(blank=True, choices=[('Front End', 'Front End'), ('Back End', 'Back End'), ('Full Stack Website', 'Full Stack Website'), ("I'm not sure yet", "I'm not sure yet")], max_length=50, null=True),
        ),
    ]
