# Generated by Django 4.2.9 on 2024-02-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0011_alter_contact_days_alter_contact_web'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
                ('profile', models.ImageField(upload_to='images')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('mobile', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
