# Generated by Django 4.2.7 on 2024-05-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_gallerycategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Galary/'),
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Galary/'),
        ),
    ]
